// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3MMaOJmYzGm38oxrfr2v2l6DnGL2H1pw',
    appId: '1:176318087599:web:b9b679f10b2b9d914e2f5a',
    messagingSenderId: '176318087599',
    projectId: 'eventlymobileapplication',
    authDomain: 'eventlymobileapplication.firebaseapp.com',
    storageBucket: 'eventlymobileapplication.firebasestorage.app',
    measurementId: 'G-FM16P5KQJC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOzQ9MPwuFcE-eb9yrtWvCYWp_NcJg7ks',
    appId: '1:176318087599:android:f30ccaa35282f0b04e2f5a',
    messagingSenderId: '176318087599',
    projectId: 'eventlymobileapplication',
    storageBucket: 'eventlymobileapplication.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBB5X3zFG6TC3xJsAis3kGCfERuML1AR-8',
    appId: '1:176318087599:ios:42aff55f914e05024e2f5a',
    messagingSenderId: '176318087599',
    projectId: 'eventlymobileapplication',
    storageBucket: 'eventlymobileapplication.firebasestorage.app',
    iosBundleId: 'com.example.eventlyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBB5X3zFG6TC3xJsAis3kGCfERuML1AR-8',
    appId: '1:176318087599:ios:42aff55f914e05024e2f5a',
    messagingSenderId: '176318087599',
    projectId: 'eventlymobileapplication',
    storageBucket: 'eventlymobileapplication.firebasestorage.app',
    iosBundleId: 'com.example.eventlyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3MMaOJmYzGm38oxrfr2v2l6DnGL2H1pw',
    appId: '1:176318087599:web:d37fda02b0667d624e2f5a',
    messagingSenderId: '176318087599',
    projectId: 'eventlymobileapplication',
    authDomain: 'eventlymobileapplication.firebaseapp.com',
    storageBucket: 'eventlymobileapplication.firebasestorage.app',
    measurementId: 'G-ZEJZF8CF5W',
  );
}
